runtime: nodejs18
env: standard
instance_class: F4

automatic_scaling:
  max_instances: 5
  min_instances: 1
  target_cpu_utilization: 0.6

env_variables:
  GCP_PROJECT_ID: "asset-property-listing-be"
  NODE_ENV: "production"
  GCP_PROJECT: 496046152894
  PORT: 8080

# Increased resources for handling large payloads
resources:
  cpu: 2
  memory_gb: 2
  disk_size_gb: 10

# Health check configuration
readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2

handlers:
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto
